# See full list of defaults here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# To see all cops used see here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/dummy/**/*'
    - 'Gemfile'
    - 'gemfiles/*.gemfile'
  DisplayStyleGuide: true
  DisplayCopNames: true
  TargetRubyVersion: 3.2
  TargetRailsVersion: 7.2

Layout/ParameterAlignment:
  Enabled: false

Layout/CaseIndentation:
  IndentOneStep: true

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Max: 140

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousOperator:
  Exclude:
    - 'spec/**/*'

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'spec/**/*'

Lint/BooleanSymbol:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 250

Metrics/PerceivedComplexity:
  Exclude:
    - 'spec/**/*'

Performance/RedundantMatch:
  Enabled: false

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: false

Rails/Delegate:
  EnforceForPrefixed: false

Rails/FindEach:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Exclude:
    - 'app/models/test_track/remote/**/*'

Rails/HttpPositionalArguments:
  Enabled: false

Rails/OutputSafety:
  Enabled: true

Rails/RakeEnvironment:
  Exclude:
    - 'Rakefile'

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Exclude:
    - 'app/views/**/*.jbuilder'

Style/MissingElse:
  Enabled: true
  EnforcedStyle: case

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Naming/PredicateName:
  NamePrefix:
    - is_
  ForbiddenPrefixes:
    - is_

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/YodaCondition:
  Enabled: false
