language: ruby

branches:
  only:
  - master

rvm:
- 2.5.7
- 2.6.5
- 2.7.0

before_install:
- gem update --system
- gem install bundler

before_script:
- RAILS_ENV=test bundle exec rake db:setup

gemfile:
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
