language: ruby

rvm:
- 2.3.1
- 2.4.2
- 2.6.1

before_install:
- gem update --system
- gem install bundler

before_script:
- RAILS_ENV=test bundle exec rake db:setup

gemfile:
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile

matrix:
  exclude:
    - rvm: 2.3.1
      gemfile: gemfiles/rails_6_0.gemfile
    - rvm: 2.4.2
      gemfile: gemfiles/rails_6_0.gemfile
