default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  url: 'sqlite3:db/development.sqlite3'

test:
  <<: *default
  url: 'sqlite3:db/test.sqlite3'

production:
  <<: *default
  url: 'sqlite3:db/production.sqlite3'
