require 'rails_helper'

RSpec.describe TestTrack::Assignment do
  describe "#variant" do
    it "returns a variant generated by VariantCalculator"

    it "returns nil when TestTrack is offline"
  end
end
