require 'rails_helper'

RSpec.describe TestTrack::Assignment do
  describe "#variant" do
    let(:visitor) { instance_double(TestTrack::Visitor) }
    let(:variant_calculator) { instance_double(TestTrack::VariantCalculator, variant: "the_variant") }

    subject { described_class.new(visitor, "split_name") }

    before do
      allow(TestTrack::VariantCalculator).to receive(:new).and_return(variant_calculator)
    end

    context "when the visitor is known" do
      before do
        allow(visitor).to receive(:known_visitor?).and_return(true)
      end

      it "returns a variant generated by VariantCalculator" do
        expect(subject.variant).to eq "the_variant"
        expect(variant_calculator).to have_received(:variant)
      end
    end

    context "when the visitor is unknown" do
      before do
        allow(visitor).to receive(:known_visitor?).and_return(false)
      end

      it "returns nil when TestTrack is offline" do
        expect(subject.variant).to eq nil
        expect(variant_calculator).not_to have_received(:variant)
      end
    end
  end
end
