require 'rails_helper'

RSpec.describe TestTrack::Assignment do
  let(:visitor) { instance_double(TestTrack::Visitor, offline?: offline) }
  let(:offline) { false }

  subject { described_class.new(visitor, :split_name) }

  describe "#split_name" do
    it "returns a string" do
      expect(subject.split_name).to be_kind_of String
    end
  end

  describe "#variant" do
    let(:variant_calculator) { instance_double(TestTrack::VariantCalculator, variant: :the_variant) }

    before do
      allow(TestTrack::VariantCalculator).to receive(:new).and_return(variant_calculator)
    end

    it "returns a string" do
      expect(subject.variant).to be_kind_of String
    end

    context "when the visitor is online" do
      it "returns a variant generated by VariantCalculator" do
        expect(subject.variant).to eq "the_variant"
        expect(variant_calculator).to have_received(:variant)
      end
    end

    context "when the visitor is offline" do
      let(:offline) { true }

      it "returns nil" do
        expect(subject.variant).to eq nil
        expect(variant_calculator).not_to have_received(:variant)
      end
    end
  end
end
